### PR TITLE
Update translation files and add Danish translations

### PR DESCRIPTION
**Pull request by cabgfx**
First off, thanks for an awesome plugin! :+1:

As I was translating it to Danish, I found a couple of issues:
1. The search path seemed to be an absolute path on your Mac
2. There's was a string in the WP admin widget that wasn't ready for translation

I've fixed both of these and simultaneously added Danish translation files.

### CODE REVIEW

**Comment by MZAWeb** [comment]
Hey! Thank you for this. And sorry for the delay.

It looks great, but please in the README give you props right besides the "Danish" translator, not in the Contributors header tag. The rest looks fine for merge.

**Comment by cabgfx** [comment]
Ok, no problem. Just to be clear: you'd like me to submit an updated .POT without changes to Contributors header, right?

**Comment by MZAWeb** [comment]
readme

Sent from my iPhone

**Comment by cabgfx** [comment]
@MZAWeb got it, PR updated.

**Comment by MZAWeb** [comment]
Thanks!

**Pull request merged**
